### ISSUE TITLE
Problem running emacs-lsp-booster with ansible language server

### ISSUE THREAD

**Issue by okomestudio** [blahgeek/emacs-lsp-booster#18]
The emacs-lsp-booster appears to run into an issue with the ansible language server (https://github.com/ansible/ansible-language-server).

I've confirmed that my emacs-lsp-booster setup is working with other language servers. I've also confirmed that the ansible language server (`ansible-ls`) is working via LSP when emacs-lsp-booster is not in use.

When `ansible-ls` gets activated with emacs-lsp-booster present, I get the following error (in the stderr buffer):

```
[2024-03-07T02:04:02Z INFO  emacs_lsp_booster::app] Running server "/home/taro/.config/emacs/var/lsp/server/npm/@ansible/ansible-language-server/bin/ansible-language-server" "--stdio"
[2024-03-07T02:04:02Z INFO  emacs_lsp_booster::app] Will convert server json to bytecode! bytecode options: BytecodeOptions { object_type: Plist, null_value: Nil, false_value: Nil }
/home/taro/.config/emacs/var/lsp/server/npm/@ansible/ansible-language-server/lib/node_modules/@ansible/ansible-language-server/node_modules/vscode-jsonrpc/lib/common/connection.js:829
            throw new ConnectionError(ConnectionErrors.Closed, 'Connection is closed.');
                  ^

ConnectionError: Connection is closed.
    at throwIfClosedOrDisposed (/home/taro/.config/emacs/var/lsp/server/npm/@ansible/ansible-language-server/lib/node_modules/@ansible/ansible-language-server/node_modules/vscode-jsonrpc/lib/common/connection.js:829:19)
    at Object.sendNotification (/home/taro/.config/emacs/var/lsp/server/npm/@ansible/ansible-language-server/lib/node_modules/@ansible/ansible-language-server/node_modules/vscode-jsonrpc/lib/common/connection.js:910:13)
    at RemoteConsoleImpl.send (/home/taro/.config/emacs/var/lsp/server/npm/@ansible/ansible-language-server/lib/node_modules/@ansible/ansible-language-server/node_modules/vscode-languageserver/lib/common/server.js:99:33)
    at RemoteConsoleImpl.error (/home/taro/.config/emacs/var/lsp/server/npm/@ansible/ansible-language-server/lib/node_modules/@ansible/ansible-language-server/node_modules/vscode-languageserver/lib/common/server.js:86:14)
    at /home/taro/.config/emacs/var/lsp/server/npm/@ansible/ansible-language-server/lib/node_modules/@ansible/ansible-language-server/node_modules/vscode-jsonrpc/lib/common/connection.js:1086:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 1
}

Node.js v20.5.1

Process ansible-ls stderr finished
```

`ansible-ls` fails to start and leads LSP to prompt me to restart it or not. Restart keeps failing with the same error message. Disabling emacs-lsp-booster and restarting `ansible-ls` works again.

**Comment by blahgeek** [comment]
Seems to be a duplicate of https://github.com/blahgeek/emacs-lsp-booster/issues/15#issuecomment-1897673045

**Comment by okomestudio** [comment]
Thank you very much for the quick response and the pointer, and I'm sorry that I missed the similar report. I was able to fix the problem in the `ansible-ls` side following the tickets. Closing as the issue is more appropriate to be fixed there.
